.

diff --git a/Dockerfile.prod b/Dockerfile.prod
--- a/Dockerfile.prod
+++ b/Dockerfile.prod
@@ -2,10 +2,13 @@ FROM python:3.12-slim-bookworm
 
 # Установка системных зависимостей
 RUN apt-get update && apt-get install -y \
+    curl \
     gettext \
     libpq-dev \
     gcc \
-    curl \
+    git \
+    libjpeg-dev \
+    zlib1g-dev \
     && rm -rf /var/lib/apt/lists/*
 
 RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin
@@ -24,11 +27,11 @@ WORKDIR /app
 COPY pyproject.toml uv.lock* /app/
 
 # Устанавливаем зависимости СИСТЕМНО (в Docker это ок и проще для Gunicorn)
-RUN uv pip install --system -r pyproject.toml
+RUN uv pip install --system --verbose -r pyproject.toml
 
 # Копируем код проекта
 COPY . /app/
-RUN chmod +x /app/justfile
+RUN chmod +x /app/Justfile || chmod +x /app/justfile || echo "Justfile not found to chmod"
 
 # Открываем порт
 EXPOSE 8000
